# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: mktc
  username: jonatasdp
  password:

test:
  adapter: postgresql
  database: churumelas_test
  username: jonatasdp
  password:

production:
  adapter: postgresql
  username: jonatasdp
  password:
  database: mktc_production
