# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: churumelas
  username: churumelas
  password: churu

test:
  adapter: postgresql
  database: churumelas_test
  username: churumelas
  password: churu

production:
  adapter: postgresql
  database: xurumelas_production
  username: root
  password: 1qazxsw2#$
  socket: /var/run/mysqld/mysqld.sock
